# Generated by Django 5.0.1 on 2026-01-25 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city_part', models.CharField(blank=True, max_length=50)),
                ('neighborhood', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('scraper', models.CharField(db_index=True, max_length=50)),
                ('link', models.URLField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(db_index=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('disposition', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(db_index=True, default='Praha', max_length=50)),
                ('city_part', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='Česko', max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('last_ping_status', models.IntegerField(blank=True, null=True)),
                ('last_ping_is_valid', models.BooleanField(db_index=True, default=True)),
                ('batch_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'city_part', 'price', 'last_ping_is_valid'], name='apartments__city_71a4b3_idx')],
                'unique_together': {('scraper', 'remote_id')},
            },
        ),
        migrations.CreateModel(
            name='StreetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(db_index=True, max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('full_address', models.CharField(blank=True, max_length=500)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('district_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartments.district')),
            ],
            options={
                'unique_together': {('street_name', 'postal_code')},
            },
        ),
    ]
